### ISSUE TITLE
warn if there are multiple lockfiles

### ISSUE THREAD

**Issue by smarlhens** [smarlhens/github-filter-npm-repos-to-empower#41]
- package-lock.json + yarn.lock
- package-lock.json + pnpm-lock.yaml
- yarn.lock + pnpm-lock.yaml

**Comment by SrinjayKapri7** [comment]
i want to work in this repo, but the issue is not clear to me

**Comment by smarlhens** [comment]
Hey !

Thanks for reaching out !

This issue is about repository that are in transition from a package manager to another and keeping multiple lockfiles like describe in my first messages. 

The analysis to determine if the repository can be improved is based on the package.json and a lockfile. If there are several lockfiles, the question is which one to choose. Until we find a way to choose, the goal is simply to ignore repositories with multiple lockfiles (already implemented).

This issue documents the thinking behind multi-lockfile management.
